set nocompatible

syntax on
color gruvbox

set background=dark
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set incsearch
set viminfo=""
set ruler
set nowrap
set noswapfile
set encoding=utf-8 " displayed
set fileencoding=utf-8 " written
set autoindent
set smartindent

autocmd FileType make set noexpandtab
