set nocompatible

syntax on
colorscheme paramount

set background=dark
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set incsearch
set viminfo=""
set ruler
set noswapfile
set encoding=utf-8 " displayed
set fileencoding=utf-8 " written
set autoindent
set smartindent
set laststatus=2

autocmd FileType make set noexpandtab
